config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { passwords: 'passwords' }
  resources :users, only: [:show]
  resources :events
  resources :event_attendance, except: [:index]

  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validate :event_date_cannot_be_in_past
  validates :date, :description, presence: true

  validates :name, length: { in: 5..100 }, presence: true
  validates :location, length: { in: 5..100 }, presence: true

  belongs_to :creator, class_name: 'User'
  has_many :event_attendance, dependent: :destroy

  has_many :invitations, -> { where(attendance_status: :invited) },
           class_name: 'EventAttendance'

  has_many :attendees, -> { where(event_attendance: { attendance_status: :attending }) },
           through: :event_attendance, source: :user

  scope :future, -> { where('date >= ?', Date.today) }
  scope :past, -> { where('date < ?', Date.today) }

  scope :latest_first, -> { order(date: :desc) }
  scope :earliest_first, -> { order(date: :asc) }

  # scopes named public and private not viable as they
  # conflict with ActiveRecord method names
  scope :public_visible, -> { where(private: false) }
  scope :private_visible, -> { where(private: true) }

  def event_date_cannot_be_in_past
    return true if date.nil?

    errors.add(:date, "can't be in the past") if date < Date.today
  end

  def upcoming?
    date >= Date.today
  end
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  self.table_name = 'event_attendance'

  enum attendance_status: { invited: 0, attending: 1 }

  belongs_to :user
  belongs_to :event

  scope :pending_for_upcoming_events, -> { invited.joins(:event).merge(Event.future) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id'
  has_many :event_attendance

  has_many :invitations, -> { where(attendance_status: :invited) },
           class_name: 'EventAttendance'

  has_many :attended_events, -> { where(event_attendance: { attendance_status: :attending }) },
           through: :event_attendance, source: :event

  def attending?(event)
    attended_events.include?(event)
  end

  def invited?(event)
    invitations.include?(event.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendance_controller.rb
class EventAttendanceController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def create
    user = attending_user(params[:event_attendance][:email])

    if user.nil? || user == current_user
      flash[:alert] = 'Invalid user'
      redirect_to event_path(params[:event_attendance][:event_id])
      return
    end

    if EventAttendance.exists?(event_id: params[:event_attendance][:event_id], user_id: user.id)
      flash[:alert] = 'User is already invited or attending'
      redirect_to event_path(params[:event_attendance][:event_id])
      return
    end

    @event_attendance = user.event_attendance.build(event_attendance_params)
    @event_attendance.save

    redirect_to event_path(@event_attendance.event_id)
  end

  def update
    @event_attendance = EventAttendance.find(params[:id])
    @event_attendance.update(event_attendance_params)

    event_id = @event_attendance.event_id
    redirect_to event_path(event_id)
  end

  def destroy
    @event_attendance = EventAttendance.find(params[:id])
    event_id = @event_attendance.event_id

    @event_attendance.destroy
    redirect_to event_path(event_id)
  end

  private

  def event_attendance_params
    params.require(:event_attendance).permit(:event_id, :user_id, :attendance_status)
  end

  def attending_user(email)
    if email
      User.find_by_email(email)
    else
      current_user
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])

    if user_signed_in?
      @user_event_attendance = EventAttendance.find_or_initialize_by(user_id: current_user.id, event_id: @event.id)
    end

    @email_invite_event_attendance = @event.event_attendance.build
    @attendees = @event.attendees
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to event_path(@event.id)
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])

    if @event.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :date, :private, :description)
  end

  def attending_user(email)
    if email
      User.find_by_email(email)
    else
      current_user
    end
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
  def create
    flash.now[:alert] = 'This functionality is disabled.  You would normally receive an email with reset instructions.'

    self.resource = resource_class.new
    render 'new'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    # prevent accessing another user's page because the create event button is not protected
    redirect_to user_path(current_user.id) if params[:id] != current_user.id.to_s

    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendance_helper.rb
module EventAttendanceHelper
  def invitation_button_text(event_attendance)
    case event_attendance.attendance_status
    when :invited.to_s
      'Accept Invitation'
    when :attending.to_s
      'Quit Attending'
    else
      'Attend'
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_button_text(event)
    if event.persisted?
      'Save'
    else
      'Create'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendance/_form.html.erb
<%= form_with model: event_attendance do |form| %>
  <%= form.hidden_field :event_id, value: event_attendance.event_id %>
  <%= form.hidden_field :user_id, value: event_attendance.user_id %>
  <%= form.hidden_field :attendance_status, value: :attending %>
  <%= form.submit invitation_button_text(event_attendance), class: 'button-sm bordered' %>
<% end %>

app/views/event_attendance/_invite_by_email_form.html.erb
<h4>Invite by Email</h4>
<%= form_with model: event_attendance, url: event_attendance_index_path do |form| %>
  <%= form.hidden_field :event_id, value: event_attendance.event_id %>
  <%= form.hidden_field :attendance_status, value: :invited %>
  <%= form.label :email %>
  <br>
  <%= form.email_field :email, class: 'stackable-sm' %>
  <%= form.button 'Invite', type: 'submit', class: 'button-sm bordered' %>
<% end %>

app/views/events/_attendees_list.html.erb
<h3>Attendees</h3>

<% if event.attendees.count > 0 %>
  <ul>
    <% event.attendees.each do |attendee| %>
      <li class="stackable-sm">
        <%= attendee.email %> 

        <% if event.creator == current_user %>
          <% if attendee != current_user %>
            <%= link_to 'Remove', event_attendance_path(attendee), method: :delete, 
              data: { confirm: "Really remove this user?" }, class: 'button-xsm bordered' %>
          <%end%>
        <%end%>
      </li>
    <% end %>  
  </ul>
<% else %>
  No one is attending :(
<% end %>

app/views/events/_event.html.erb
<h3>Name</h3>
<div class="stackable-sm"><%= event.name %></div>
<h3>Host</h3>
<div class="stackable-sm"><%= event.creator.email %></div>
<h3>Location</h3>
<div class="stackable-sm"><%= event.location %></div>
<h3>Date</h3>
<div class="stackable-sm"><%= event.date %></div>
<h3>Description</h3>
<div class="stackable-sm"><%= event.description %></div>

<div class="stackable-sm"><%= render 'manage_own_attendance', event_attendance: @user_event_attendance, creator: event.creator %></div>

<% if current_user == @event.creator %>
  <div class="stackable-sm"><%= render 'event_management_links', event: @event %></div>

  <% if event.upcoming? %>
    <div class="stackable-sm"><%= render 'event_attendance/invite_by_email_form', event_attendance: @email_invite_event_attendance  %></div>
  <% end %>
<% end %>

<%= render 'attendees_list', event: event  %>
<%= render 'invitees_list', event: event  %>

app/views/events/_event_card.html.erb
<div class="event-card bordered">
  <%= link_to event_path(event) do %>
    <div class="event-card-header padded-md">
      <%= event.name %><%= ' - (private)' if event.private? %> 
    </div>

    <div class="event-card-primary-field">
      <%= event.date %>
    </div>

    <div class="event-card-primary-field">
      <%= event.location %>
    </div>

    <div class="event-card-secondary-field">
      <%= event.description %>
    </div>
  <% end %>
</div>

app/views/events/_event_card_list.html.erb
<h2 class="stackable-md"><%= title %></h2>

<div class="event-card-container stackable-md">
  <% if events.count > 0 %>
    <%= render partial: 'events/event_card', collection: events, as: :event %>
  <% else %>
   <p>No events to display.</p>
  <% end %>
</div>

app/views/events/_event_card_mini.html.erb
<div class='event-card-sm bordered'>
  <%= link_to event_path(event) do %>
    <div class="event-card-primary-field">
      <%= event.name %><%= ' - (private)' if event.private? %>
    </div>

    <div class="event-card-primary-field">
      <%= event.date %>
    </div>

    <div class="event-card-primary-field">
      <%= event.location %>
    </div>
  <% end %>
</div>

app/views/events/_event_card_mini_list.html.erb
<h4 class="stackable-sm"><%= title %></h2>

<div class="event-card-container stackable-md">
  <% if events.count > 0 %>
    <%= render partial: 'events/event_card_mini', collection: events, as: :event %>
  <% else %>
   <p>No events to display.</p>
  <% end %>
</div>

app/views/events/_event_management_links.html.erb
<h4 class="stackable-sm">Event Management</h4>
<%= link_to 'Edit', edit_event_path(event), class: 'button-sm bordered' if event.upcoming? %> 
<%= link_to 'Delete', event_path(event), method: :delete, data: { confirm: "Are you sure?" }, class: 'button-sm bordered' %>

app/views/events/_form.html.erb
<% if event.errors.any? %>
  <div class='error'>
    Errors:
    <% event.errors.each do |error| %>
    <p><%= error.full_message %></p>
    <% end %>
  <% end %>
</div>

<%= form_with model: event, class: 'event-form bordered padded-md' do |form| %>
  <%= form.label :name %>
  <br>
  <%= form.text_field :name, class: 'stackable-sm full-width' %>

  <%= form.label :location %>
  <br>
  <%= form.text_field :location, class: 'stackable-sm full-width' %>

  <%= form.label :date %>
  <br>
  <%= form.date_field :date , class: 'stackable-sm full-width'%>

  <%= form.label :description %>
  <br>
  <%= form.text_area :description, size: "30x6", class: 'stackable-sm full-width'%>

  <div class='stackable-sm'>
    <%= form.label :private, 'Public' %>
    <%= form.radio_button :private, false %>
    <%= form.label :private, 'Private' %>
    <%= form.radio_button :private, true %>
  </div>
  
  <%= form.button event_button_text(event), type: "submit", class: 'bordered' %>
<% end %>

app/views/events/_invitees_list.html.erb
<% if event.creator == current_user %>
  <h3>Pending Invitations</h3>
    <% if event.invitations.count > 0 %>
      <ul>
        <% event.invitations.includes(:user).each do |invitation| %>
          <li class="stackable-sm">
            <%= invitation.user.email %> 

            <% if event.upcoming? %>
              <%= link_to 'Cancel', event_attendance_path(invitation), method: :delete, 
                data: { confirm: "Really remove this invitation?" }, class: 'button-xsm bordered' %>
            <% end %>
          </div>
        <% end %>
      </ul>
    <% else %>
      No pending invitations
    <% end %>
<% end %>

app/views/events/_manage_own_attendance.html.erb
<% if user_signed_in? %>
  <% if creator.id != current_user.id %>
    <% if event_attendance.attending? %>
      <%= button_to invitation_button_text(event_attendance), event_attendance, method: :delete, class: 'button-sm bordered' %>
    <% else %>
      <%= render 'event_attendance/form', event_attendance: event_attendance %>
    <% end %>
  <% end %>
<% elsif  %>
  Log in or sign up to attend!
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event Page</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<h1 class="stackable-md">Public Events</h1>

<%= link_to new_event_path do %>
  <%= button_tag 'Create New Event', type: 'button', class: 'stackable-md bordered' %>
<% end %>

<%= render partial: 'event_card_list', locals: { title: 'Upcoming Events', events: @events.future.public_visible.earliest_first } %>
<%= render partial: 'event_card_list', locals: { title: 'Past Events', events: @events.past.public_visible.latest_first } %>

app/views/events/new.html.erb
<h1>New Event Page</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<h1>Event Details</h1>

<%= render 'event', event: @event %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <%= render partial: "shared/flash" %>

    <main>
      <%= yield %>
    </main>

    <%= render partial: "shared/footer" %>
  </body>
</html>

app/views/shared/_flash.html.erb
  <% if notice %>
    <p class="flash-message notice"><%= notice %></p>
  <% end %>

  <% if alert %>
    <p class="flash-message alert"><%= alert %></p>
  <% end %>
  
  

app/views/shared/_footer.html.erb
<footer>&copy; Important Event Company 2022</footer>

app/views/shared/_navbar.html.erb
    <nav tabindex="-1" onclick="this.focus()">
      <ul class="left">
        <li class="logo"><%= link_to 'Event Manager', root_path %></li>
      </ul>

      <ul class="right">
        <% if user_signed_in? %>
          <li>(<%= current_user.email %>)</li>
          <li><%= link_to "My Events", user_path(current_user) %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>

app/views/users/_user_event_list.html.erb
  <p><%= title %></p>
  <% events.each do |event| %>
    <p><%= link_to event.name, event %> - private: <%= event.private %></p> 
  <% end %>

app/views/users/_user_invitation_list.html.erb
<h2 class='stackable-md'><%= title %></h2>

<div class="event-card-container stackable-md">
  <% if invitations.count > 0 %>
    <% invitations.each do |invitation| %>
      <%= render partial: 'events/event_card_mini', locals: { event: invitation.event } %>
    <% end %>
  <% else %>
    No invitations :(
  <% end %>
</div>

app/views/users/index.html.erb
<h1>User #index</h1>

app/views/users/show.html.erb
<h1 class="stackable-md">My Events</h1>

<%= link_to new_event_path do %>
  <%= button_tag 'Create New Event', type: 'button', class: 'stackable-md bordered' %>
<% end %>

<%= render partial: 'events/event_card_list', locals: { title: 'Upcoming Events', events: @user.created_events.future.earliest_first } %>
<%= render partial: 'events/event_card_list', locals: { title: 'Past Events', events: @user.created_events.past.latest_first } %>

<hr class='stackable-sm'>

<%= render 'user_invitation_list', invitations: @user.invitations.pending_for_upcoming_events, title: 'Pending Invitations' %>

<hr class='stackable-sm'>

<h2 class='stackable-md'>My Event Attendance</h2>
<%= render partial: 'events/event_card_mini_list', locals: { title: 'Upcoming Events', events: @user.attended_events.future.earliest_first } %>
<%= render partial: 'events/event_card_mini_list', locals: { title: 'Past Events', events: @user.attended_events.past.latest_first } %>